const catelist1Elem = document.getElementById("cate-list1");
const catelist2Elem = document.getElementById("cate-list2");
const catelist3Elem = document.getElementById("cate-list3");
(async () => {
  try {
    const mainpage = (await axios.get("http://localhost:8080/product_list", {}))
      .data;

    //category
    if (mainpage[0]) {
      mainpage[0].forEach((cate1) => {
        catelist1Elem.innerHTML += `<a href="/product_list?cate1=${cate1.id}" class="cate-list">${cate1.name}</a>`;
      });
      for (let i = 0; i < catelist1.length; i++) {
        catelist1[i].onmouseover = () => {
          secondCateElem.classList.add("on");
          let secondcate = i;
          let str = "";
          if (mainpage[0][secondcate].Secondcategories) {
            mainpage[0][secondcate].Secondcategories.forEach((cate2) => {
              str += `<a href="/product_list?cate2=${cate2.id}" class="cate-list">${cate2.name}</a>`;
            });
          }
          catelist2Elem.innerHTML = str;
          for (let i = 0; i < catelist2.length; i++) {
            catelist2[i].onmouseover = () => {
              thirdCateElem.classList.add("on");
              let thirdcate = i;
              let str = "";
              if (
                mainpage[0][secondcate].Secondcategories[thirdcate]
                  .Thirdcategories
              ) {
                mainpage[0][secondcate].Secondcategories[
                  thirdcate
                ].Thirdcategories.forEach((cate3) => {
                  str += `<a href="/product_list?cate3=${cate3.id}" class="cate-list">${cate3.name}</a>`;
                });
              }
              catelist3Elem.innerHTML = str;
            };

            catelist2[i].onmousedown = () => {
              for (let a = 0; a < catelist1.length; a++) {
                catelist2[a].classList.remove("on");
              }
              catelist2[i].classList.add("on");
            };
          }
        };

        catelist1[i].onmousedown = () => {
          for (let a = 0; a < catelist1.length; a++) {
            catelist1[a].classList.remove("on");
          }
          catelist1[i].classList.add("on");
        };
      }
    }
    //
    let urlStr = window.location.href;
    let url = new URL(urlStr);
    let urlparams = url.searchParams;
    let cate1 = urlparams.get("cate1");
    let cate2 = urlparams.get("cate2");
    let cate3 = urlparams.get("cate3");

    if (cate1) {
      console.log("cate1");
    }
    if (cate2) {
      console.log("cate2");
    }
    if (cate3) {
      console.log("cate3");
    }
  } catch (err) {
    console.error(err);
  }
})();

//paging script
const pagelistElem = document.getElementsByClassName("page-list")[0];
const pageElem = document.getElementsByClassName("num");
const nextElem = document.getElementById("next-btn");

let user = [
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGBT",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "SAMSUNG/TV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Shaomi",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "Banill/ChinRu",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
  {
    name: "LGTV",
    price: "25000",
    location: "A시 B구 C동",
    img: "./imgs/eye.png",
  },
];
let page = 1;
let count = 40;
let pageidx = 0;
console.log(user.length);

const prdArea = document.getElementById("product-wrap");

const getPrd = async () => {
  try {
    const product = (
      await axios.post("http://localhost:8080/product_list", {
        user,
        page,
        count,
        pageidx,
      })
    ).data;

    prdArea.innerHTML = "";

    // (page -1) * count, page * count
    // 40, 80
    // page = 1, i = 0 page =2, i = 40 page 3, i = 80
    // i = page - 1

    for (let i = (page - 1) * count; i < page * count; ++i) {
      if (i < user.length) {
        prdArea.innerHTML += `<a href="#">
        <div class="product">
          <img src="${user[i].img}" />
          <div class="info">
            <p>${user[i].name}</p>
            <div>
              <span><span>${user[i].price}</span>원</span>4초전
            </div>
          </div>
          <div class="location">
            <img src="./imgs/location.png" />${user[i].location}
          </div>
        </div>
      </a>`;
      }
    }
  } catch (err) {
    console.error(err);
  }
};

getPrd();

const pageLi = async () => {
  try {
    const pagingCount = Math.floor(user.length / 40);
    const pagingElem = document.getElementById("page-list");
    const preElem = document.getElementById("pre-btn");
    pagingElem.innerHTML = "";
    preElem.innerHTML = "";
    const creLi = document.createElement("li");

    for (let i = pageidx * 10; i < pagingCount; ++i) {
      if (i < 10 * (pageidx + 1)) {
        const creLi = document.createElement("li");
        creLi.innerHTML += `<a href="#${pageidx}" class="num">${i + 1}</a>`;

        creLi.onclick = () => {
          page = i + 1;
          getPrd(page);
          console.log("i:", i);
          console.log("page:", page);
          console.log("idx:", pageidx);

          [...pageElem].forEach((item) => {
            item.classList.remove("on");
          });
          pageElem[page - pageidx * 10 - 1].classList.add("on");
        };

        pagingElem.append(creLi);
      }
    }

    for (let i = pageidx * 10; i < pagingCount; ++i) {
      if (i == 10 * (pageidx + 1)) {
        nextElem.onclick = () => {
          if (pageidx == Math.floor(pagingCount / 10)) {
            return;
          }
          pageidx += 1;
          page = pageidx * 10 + 1;
          console.log("idx: " + pageidx);
          getPrd(page);
          pageLi();
          console.log("i:", i);
          console.log("page:", page);
          console.log("idx:", pageidx);
        };
      }
    }

    for (let i = pageidx * 1; i < pagingCount; ++i) {
      if (pageidx > 0) {
        creLi.innerHTML = `<a href="#" class="pred">〈</a>`;
        creLi.onclick = () => {
          pageidx -= 1;
          page = pageidx * 10 + 10;
          console.log("idx: " + pageidx);
          getPrd(page);
          pageLi();
          console.log("i:", i);
          console.log("page:", page);
          console.log("idx:", pageidx);
        };
        preElem.append(creLi);
      }
    }

    pageElem[page - pageidx * 10 - 1].classList.add("on");
    console.log("page C:", pagingCount);
  } catch (err) {
    console.error(err);
  }
};

pageLi();
